# Generated by Django 5.0.4 on 2024-04-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('Super Admin', 'Super Admin'), ('State Admin', 'State Admin'), ('District Admin', 'District Admin'), ('Center Incharge', 'Center Incharge'), ('Examiner', 'Examiner'), ('Trainer', 'Trainer'), ('Student', 'Student')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
